// plugins/vuetify.js
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccount,
  mdiMapMarkerRadius,
  mdiCircleDouble,
  mdiMagnify,
  mdiEmail,
  mdiMapMarkerStar,
  mdiCalendarHeart,
  mdiFilter,
  mdiMenuDown,
  mdiArrowRight,
  mdiArrowLeft,
  mdiStarFourPoints,
  mdiStarFourPointsOutline,
  mdiYoutube,
  mdiPhone,
  mdiInstagram,
  mdiFacebook,
  mdiGoogle,
  mdiClose,
  mdiChevronDoubleRight,
  mdiChevronDoubleLeft,
  mdiShareVariantOutline,
  mdiTrashCanOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarkedOutline,
  mdiCart,
  mdiCamera,
  mdiAccountCircle,
  mdiPencil,
  mdiTicket,
  mdiHome,
  mdiAccountGroupOutline,
  mdiAccountHardHat,
  mdiBell,
  mdiBellBadge,
  mdiMessage,
  mdiHeart,
  mdiFlash
} from '@mdi/js'

export default defineNuxtPlugin((nuxtApp) => {
  const myCustomDarkTheme = {
    dark: true,
    colors: {
      white: '#fff',
      background: '#0f000c',
      surface: '#0f000c',
      primary: '#d946ef',
      accent: '#e9d5ff',
      'primary-darken-1': '#3700B3',
      'purple-accent-4':'#5E35B1',
      'purple-darken-4':'#4A148C',
      secondary: '#03DAC6',
      'secondary-darken-1': '#018786',
      error: '#B00020',
      info: '#2196F3',
      success: '#4CAF50',
      warning: '#FB8C00',
    },
  }

  const vuetify = createVuetify({
    theme: {
      defaultTheme: 'myCustomDarkTheme',
      themes: {
        myCustomDarkTheme,
      },
    },
    icons: {
      defaultSet: 'mdi',
      aliases: {
        ...aliases,
        account: mdiAccount,
        location: mdiMapMarkerRadius,
        online: mdiCircleDouble,
        search: mdiMagnify,
        email: mdiEmail,
        phone: mdiPhone,
        location: mdiMapMarkerStar,
        calender: mdiCalendarHeart,
        filter: mdiFilter,
        dropdownIcon: mdiMenuDown,
        nextArrow: mdiArrowRight,
        prevArrow: mdiArrowLeft,
        subscribed: mdiStarFourPoints,
        subscribe: mdiStarFourPointsOutline,
        youtube: mdiYoutube,
        instagram: mdiInstagram,
        facebook: mdiFacebook,
        google: mdiGoogle,
        cross: mdiClose,
        right: mdiChevronDoubleRight,
        left: mdiChevronDoubleLeft,
        share: mdiShareVariantOutline,
        delete: mdiTrashCanOutline,
        select: mdiCheckboxMarkedOutline,
        deselect: mdiCheckboxBlankOutline,
        cart: mdiCart,
        marker: mdiMapMarkerStar,
        camera: mdiCamera,
        accountCircle: mdiAccountCircle,
        pencil: mdiPencil,
        ticket: mdiTicket,
        home:mdiHome,
        group: mdiAccountGroupOutline,
        jobs: mdiAccountHardHat,
        notification:mdiBell,
        notificationBadge: mdiBellBadge,
        message: mdiMessage,
        heart2:mdiHeart,
        flash:mdiFlash
      },
      sets: {
        mdi,
      },
    },
  })

  nuxtApp.vueApp.use(vuetify)
})
